--------------------------------------------------------------------------------------
-- sisotest_create_database.sql
--------------------------------------------------------------------------------------
-- Descripcion : Permite crear la Base de Datos y archivos del SISO/TEST
-- Creado      : 10-01-2023
-- Autor       : MARCO SALVADOR
-------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------

USE [master]
GO
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'SISOTEST.SIMULATOR')
BEGIN
CREATE DATABASE [SISOTEST.SIMULATOR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SISOTEST', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER03\MSSQL\DATA\SISOTESTSIMULATOR.mdf' , SIZE = 9216KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SISOTEST_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER03\MSSQL\DATA\SISOTESTSIMULATOR_log.ldf' , SIZE = 5095872KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
END
GO


USE [SISOTEST.SIMULATOR]
GO

IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE name = N'SISOTEST_DAT')
BEGIN
ALTER DATABASE [SISOTEST.SIMULATOR] ADD FILEGROUP [SISOTEST_DAT]
END
GO

IF NOT EXISTS (SELECT name FROM sys.database_files WHERE name = N'SISOTEST_DAT')
BEGIN
ALTER DATABASE [SISOTEST.SIMULATOR] ADD FILE
(
NAME = N'SISOTEST_DAT', 
FILENAME=N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER03\MSSQL\DATA\SISOTEST_DAT.ndf', 
SIZE = 3103744 KB,
MAXSIZE = UNLIMITED, 
FILEGROWTH = 10%
)
TO FILEGROUP [SISOTEST_DAT]
END
GO

IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE name = N'SISOTEST_IDX')
BEGIN
ALTER DATABASE [SISOTEST.SIMULATOR] ADD FILEGROUP [SISOTEST_IDX] 
END
GO

IF NOT EXISTS (SELECT name FROM sys.database_files WHERE name = N'SISOTEST_IDX')
BEGIN
ALTER DATABASE [SISOTEST.SIMULATOR] ADD FILE
(
NAME = N'SISOTEST_IDX', 
FILENAME=N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER03\MSSQL\DATA\SISOTEST_IDX.ndf', 
SIZE = 316416 KB, 
MAXSIZE = UNLIMITED, 
FILEGROWTH = 10%
)
TO FILEGROUP [SISOTEST_IDX]
END
GO

USE [master]
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SISOTEST.SIMULATOR].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET ARITHABORT OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET RECOVERY FULL 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET  MULTI_USER 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'SISOEFT.CMACICA', N'ON'
GO
USE [master]
GO
ALTER DATABASE [SISOTEST.SIMULATOR] SET  READ_WRITE 
GO


